version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url-shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./url-shortener-api
    image: url-shortener-api
    env_file:
      - ./url-shortener-api/.env
    ports:
      - "3001:3001"
    depends_on:
      - db

  ui:
    build:
      context: ./url-shortener-ui
    image: url-shortener-ui
    env_file:
      - ./url-shortener-ui/.env
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data: 